AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for qldb

Parameters:
  QldbLedger:
    Description: Name of QLDB Ledger
    Type: String
    Default: ApiLedger
  TopicName:
    Description: Name of Topic to send events to
    Type: String
    Default: ApiEvents
  StreamName:
    Description: Name of Kinesis Stream
    Type: String
    Default: ApiLedgerStream

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: api/
      FunctionName: Qldb-Api
      Handler: api.app.handler
      Runtime: python3.8
      Timeout: 30
      MemorySize: 256
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Sid: LedgerPermissions
              Effect: Allow
              Action:
                - qldb:SendCommand
              Resource:
                - !Sub arn:aws:qldb:${AWS::Region}:${AWS::AccountId}:ledger/${QldbLedger}
            - Sid: TablePermissions
              Effect: Allow
              Action:
                - qldb:PartiQLSelect
                - qldb:PartiQLInsert
                - qldb:PartiQLUpdate
              Resource:
                # All Tables, but if we know the table-id (not name) this can be restricted to the ApiEvent table
                - !Sub arn:aws:qldb:${AWS::Region}:${AWS::AccountId}:ledger/${QldbLedger}/table/*
        - SNSPublishMessagePolicy:
            TopicName: !Ref TopicName
      Environment:
        Variables:
          QLDB_LEDGER: !Ref QldbLedger
          TOPIC_ARN: !Sub arn:aws:sns:${AWS::Region}:${AWS::AccountId}:${TopicName}
      Events:
        Api:
          Type: HttpApi

  StreamFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: stream/
      FunctionName: Qldb-Stream
      Handler: stream.app.handler
      Runtime: python3.8
      Timeout: 120
      MemorySize: 256
      Events:
        Stream:
          Type: Kinesis
          Properties:
            Stream: !Sub arn:aws:kinesis:${AWS::Region}:${AWS::AccountId}:stream/${StreamName}
            StartingPosition: TRIM_HORIZON
            MaximumRetryAttempts: 0

Outputs:
  QldbApiApi:
    Description: API Gateway endpoint URL
    Value: !GetAtt ServerlessHttpApi.ApiEndpoint
